--- #YAML:1.0
name:                POE-Component-Client-Keepalive
version:             0.1000
abstract:            Manages and keeps alive client connections
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    POE:                           0.31
    POE::Component::Client::DNS:   0.9801
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Rocco Caputo <rcaputo@cpan.org>
no_index:
    dir:
        - mylib
