--- #YAML:1.0
name:               POE-Component-Client-Keepalive
version:            0.25
abstract:           Manages and keeps alive client connections
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:                  0.31
    POE::Component::Client::DNS:  1.01
no_index:
    directory:
        - t
        - inc
        - mylib
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
