---
abstract: 'manage connections, with keep-alive'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-Keepalive
requires:
  Net::IP: 1.25
  POE: 1.294_512
  POE::Component::Resolver: 0.900_161
  POE::Wheel::SocketFactory: 1.294_512
resources:
  repository: git://github.com/rcaputo/poe-component-client-keepalive.git
version: 0.263_161
